### ISSUE TITLE
Could not find a declaration file for module '@toast-ui/react-calendar'

### ISSUE THREAD

**Issue by srud-salam** [nhn/toast-ui.react-calendar#10]
## Version

"@toast-ui/react-calendar": "^1.0.2",

## Test Environment

SharePoint Framework Extension

## Current Behavior

It works but throws a type warning, thought to raise: 
Could not find a declaration file for module '@toast-ui/react-calendar'. responsive-calendar/node_modules/@toast-ui/react-calendar/dist/toastui-react-calendar.js' implicitly has an 'any' type.
  Try `npm install @types/toast-ui__react-calendar` if it exists or add a new declaration (.d.ts) file containing `declare module '@toast-ui/react-calendar';`

```js
// Write example code
```

## Expected Behavior

Support Typescript please, thank you in advance

**Comment by jungeun-cho** [comment]
@srud-salam 
Sooner or later, declaration files will be added to the wrapper(vue-wrapper, react-wrapper) repository.
If you are in a hurry
https://github.com/nhn/tui.calendar/blob/master/index.d.ts
See here.

**Comment by srud-salam** [comment]
thank you
