### ISSUE TITLE
I cannot specify className when creating the calendar in render function

### ISSUE THREAD

**Issue by acolea-btig** [nhn/toast-ui.react-calendar#13]
## Version

1.0.3

## Test Environment

Chrome on MacOS and Windows
I am using typescript

## Current Behavior

```js
// example code
<Calendar
          className="calendarDiv"
          ref={this.calendarRef}
          {...calendarOptions}
/>
```

**className** is no longer recognized and it does not compile in 1.0.3

## Expected Behavior

Ability to be able to specify a CSS class
This code above works just fine in 1.0.2

**Comment by jungeun-cho** [comment]
@acolea-btig 
The Prop type must be specified so that HTML property can be used.
Please take a cup of coffee. I will solve it shortly.

**Comment by jungeun-cho** [comment]
@acolea-btig
* Deployed in [v1.0.4](https://github.com/nhn/toast-ui.react-calendar/releases/tag/v1.0.4)
