### ISSUE TITLE
timegridDisplayPrimaryTime is not working. but timegridDisplayPrimayTime is works.

### ISSUE THREAD

**Issue by iamchanii** [nhn/toast-ui.react-calendar#18]
## Version
- @toast-ui/react-calendar: ^1.0.4
- tui-calendar: ^1.12.5

## Test Environment
- macOS 10.14.6(18G95)
- chrome 77.0.3865.90 64bit

## Current Behavior
I tried to customize time hour text to display 24hours format. I read tui-calendar documentation and according to it, `timegridDisplayPrimayTime` template is deprecated. but currently, `timegridDisplayPrimayTime` is only working template to do what I want.

```ts
const template: ITemplateConfig = {
    // ...
    timegridDisplayPrimayTime: time => {
        return 'this is deprecated.';
    },
    timegridDisplayPrimaryTime: time => {
        return 'but this is not working.';
    },
   // ...
};
```

![image](https://user-images.githubusercontent.com/26643843/66371767-33599b00-e9df-11e9-9e68-790a08c59891.png)

## Expected Behavior
Display `timegridDisplayPrimaryTime` function returned. is there what I missed?

**Comment by jungeun-cho** [comment]
@iamchanii 

It's a bug
First use `timegridDisplayPrimayTime`.
