### ISSUE TITLE
bindEventHandlers is never off event when use useCallback hook.

### ISSUE THREAD

**Issue by iamchanii** [nhn/toast-ui.react-calendar#19]
## Version
- @toast-ui/react-calendar: 1.0.4

## Test Environment
- macOS 10.14.6
- chrome 76

## Current Behavior
- reproduce: [https://codesandbox.io/s/white-moon-xe6zw](https://codesandbox.io/s/white-moon-xe6zw)
- There is `onClickSchedule` event handler that wrapped with useCallback hook.
- Click test schedule. alert is display just once.
- Click rerender button and click test schedule again. alert is display twice.

## Expected Behavior
- `onClickSchedule` should called only 1 time.

Please check `bindEventHandlers` method in `index.js`. there is a logic what compare event handlers with previous. I think it have to call `off()` before call `on()` every event handlers even if equals.

**Comment by iamchanii** [comment]
https://github.com/nhn/toast-ui.react-calendar/pull/6 PR 에서 관련된 작업이 이뤄졌음을 확인했습니다. 다만 히스토리는 찾을 수 없어서 draft pr 로 올렸습니다. 리뷰 해 주시면 감사하겠습니다.

**Comment by iamchanii** [comment]
Quick fix: Write event handler as inline.

**Comment by jungeun-cho** [comment]
@iamchanii 
Please check my feedback on your PR.
Sorry for late.
