### ISSUE TITLE
Focusing the calendar month view to the specific month

### ISSUE THREAD

**Issue by andreja-ttg** [nhn/toast-ui.react-calendar#33]
Hey everyone, is there any option when creating an event in the calendar to focus on a specific month. For example, we are today in April, but when I create an event that will be in September, to automatically change the calendar month view in September?

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/Calendar#setDate

You can use `setDate` to enter the date you want to view.

```js
const calendarInstance = this.calendarRef.current.getInstance();

calendarInstance.setDate(new Date(2020, 8, 1));
```

**Comment by andreja-ttg** [comment]
Great, this works. Thanks
