### ISSUE TITLE
ref prop is not exist in calendar  ==> so i can not use instance method

### ISSUE THREAD

**Issue by naram-dash** [nhn/toast-ui.react-calendar#39]
## Version
"@toast-ui/react-calendar": "^1.0.5"
"tui-calendar": "^1.12.13"

## Test Environment
"next": "9.3.6
Microsoft Edge 84.0.522.40

## Current Behavior
Cannot find ref prop in Calendar

 _Property 'ref' does not exist on type 'IntrinsicAttributes & IOptions & EventMaps & { height: string; view?: string | undefined; schedules?: ISchedule[] | undefined; } & HTMLAttributes<...> & { ...; }'._

```typescript
const MonthlyCalendar: FC<MonthlyCalendarProps> = function (props) {
  const ref = useRef()
  return (
    <Box display="flex" flexDirection="column" alignItems="stretch" pt={3} pb={3}>
      <Header />
      <Calendar 
        {...defaultProps} 
        ref={ref}  // ERROR HERE
        view="month" 
        height="800px" 
        {...props} />
    </Box>
  )
}
  )
}
```

## Expected Behavior

ref prop exists

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-20T13:13:20
          
          
            * 메일 제목 : 
[nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by dongsik-yoo** [comment]
@jungeun-cho Check this issue please.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-20T20:06:20
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by jungeun-cho** [comment]
@naram-dash 
TOAST UI Calendar does not support SSR.
Please check the usage on next.js.
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

```js
import dynamic from 'next/dynamic';

const TuiCalendar = dynamic(() => import('@toast-ui/react-calendar').then(m => m), { ssr: false });

...

<TuiCalendar height="1000px"></TuiCalendar>
```

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-21T17:37:20
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by naram-dash** [comment]
Thank you! It works!! 

there was confusing moment at importing Calendar because tui-calendar has Calendar and @toast-ui/react-calendar also has Calendar...

Below codes are my codes in Typescript

**TUICalendarWrapper.tsx**
```typescript
import React, { HTMLAttributes, FC, LegacyRef } from 'react'
import Calendar, { EventMaps } from '@toast-ui/react-calendar'
import { IOptions, ISchedule } from 'tui-calendar'

export type TUICalendarProps = IOptions &
  EventMaps & {
    height: string
    view?: string
    schedules?: ISchedule[]
  } & HTMLAttributes<HTMLElement>

export type TUICalendarPropsWithRef = {
  forwardedRef: LegacyRef<Calendar>
} & TUICalendarProps

const TUICalendarWrapper: FC<TUICalendarPropsWithRef> = function (props) {
  return <Calendar {...props} ref={props.forwardedRef} />
}

export default TUICalendarWrapper
```

**TUICalendar.tsx**
```typescript
import React, { forwardRef } from 'react'
import dynamic from 'next/dynamic'
import Calendar from '@toast-ui/react-calendar'
import { TUICalendarProps } from './TUICalendarWrapper'
const TuiCalendar = dynamic(() => import('./TUICalendarWrapper'), { ssr: false })

const TUICalendarWithForwardedRef = forwardRef<Calendar, TUICalendarProps>(
  function forwardRefTUICalendar(props, ref) {
    return <TuiCalendar {...props} forwardedRef={ref} />
  }
)

export default TUICalendarWithForwardedRef
```

**somewhere...**
```typescript
...
import Calendar from '@toast-ui/react-calendar'
import TUICalendarWithForwardedRef from './TUICalendar'
import { TUICalendarProps } from './TUICalendarWrapper'

interface MonthlyCalendarProps extends TUICalendarProps {
  // const ref = useRef<Calendar>(null)
  calRef: RefObject<Calendar>
  boxProps?: BoxProps
}
const MonthlyCalendar: FC<MonthlyCalendarProps> = function ({ calRef, ...props }) {
  return (
    <Box display="flex" flexDirection="column" alignItems="stretch" pt={3} pb={3}>
      <Header calRef={calRef} />
      <TUICalendarWithForwardedRef {...defaultProps} ref={calRef} view="month" {...props} />
    </Box>
  )
}
...
```

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-22T13:41:20
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-22T13:41:45
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by approached** [comment]
@jungeun-cho If i change my state, i have no more the reference for the calendar instance. Do you also use state with ref in combination?

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2021-09-11T06:33:41
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by adhrinae** [comment]
@approached Could you provide an example reproducing the error so that I can check it?
Codesandbox, Stackblitz sandboxes would be great.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2021-09-13T09:46:43
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.react-calendar] ref prop is not exist in calendar ==> so i can not use instance method (#39)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by yuxiang-zhang** [comment]
@adhrinae I tried [this solution](https://github.com/nhn/toast-ui.react-calendar/issues/36#issuecomment-660766011) and also the one @jungeun-cho put above. 
It works wonders when I run the server with next dev. 
next build also succeeds, now my problem is when I do next start to run the optimized production version. 
Instead of the calendar I see `Application error: a client-side exception has occurred (see the browser console for more information)`

Here are two examples of errors from the browser console: 

```
TypeError: Cannot read properties of undefined (reading 'createElement')
    at new l (8898206d.271461cbb2f9a4d9.js:1:168485)
    at new o (8898206d.271461cbb2f9a4d9.js:1:164885)
    at 8898206d.271461cbb2f9a4d9.js:1:111041
    at f (441.7a1f7f007f9407e8.js:1:11644)
    at Object.h [as forEach] (441.7a1f7f007f9407e8.js:1:11799)
    at 8898206d.271461cbb2f9a4d9.js:1:110975
    at f (441.7a1f7f007f9407e8.js:1:11644)
    at Object.h [as forEach] (441.7a1f7f007f9407e8.js:1:11799)
    at a.exports (8898206d.271461cbb2f9a4d9.js:1:110525)
    at s.changeView (8898206d.271461cbb2f9a4d9.js:1:102232)

TypeError: Cannot read properties of null (reading 'destroy')
    at t.value (441.7a1f7f007f9407e8.js:1:6311)
    at oh (framework-433e73989db4e225.js:1:87751)
    at uh (framework-433e73989db4e225.js:1:89601)
    at Bi (framework-433e73989db4e225.js:1:101643)
    at b.unstable_runWithPriority (framework-433e73989db4e225.js:1:129126)
    at Se (framework-433e73989db4e225.js:1:44859)
    at Ai (framework-433e73989db4e225.js:1:99588)
    at ni (framework-433e73989db4e225.js:1:95688)
    at framework-433e73989db4e225.js:1:45085
    at b.unstable_runWithPriority (framework-433e73989db4e225.js:1:129126)
```
