### ISSUE TITLE
How to set current date on mounted

### ISSUE THREAD

**Issue by yepyeel** [nhn/toast-ui.react-calendar#50]
![image](https://user-images.githubusercontent.com/46668343/113125611-5cac5d80-9249-11eb-9739-34a9947e2ff8.png)

**Comment by Melissacinta** [comment]
did you find a way to implement this?

**Comment by yepyeel** [comment]
> did you find a way to implement this?

I wrote a toolbar component. You can use `getInstance` to get calendar date and you also can set a default time on your customized toolbar component

**Comment by Melissacinta** [comment]
Thanks this helped a lot
