### ISSUE TITLE
how can i custoize useDetailPopup useCreationPopup ui templete in ReactJs? 

### ISSUE THREAD

**Issue by shakil-brl** [nhn/toast-ui.react-calendar#68]
## Version

Type definitions for TOAST UI Calendar v1.15.3
TypeScript Version: 3.2.1

      calendarInstRef.current.on("clickSchedule", function (event) {
        alert(JSON.stringify(event.schedule));
        var schedule = event.schedule;
      });

how can I pass html or overtight this ui 
I am using react and nextjs  now I want to customize this useDetailPopup  with different HTML/CSS UI , 

## Expected Behavior

![image](https://user-images.githubusercontent.com/76032597/161729588-1d948b83-ad8e-494d-b90a-4d99da3813c2.png)

**Comment by adhrinae** [comment]
@shakil-brl 
It doesn't have an option to customize the default popup.
But you can make your own popup and handle it on certain events.
Please refer to this comment.

https://github.com/nhn/tui.calendar/issues/812#issuecomment-849625066

**Comment by shakil-brl** [comment]
![image](https://user-images.githubusercontent.com/76032597/161924429-aaef701d-838a-4c57-b2cf-b6bb9df81c02.png)
@[adhrinae](https://github.com/adhrinae)

How can i get this position style in  clickSchedule ? 
` calendarInstRef.current.on("clickSchedule", function (event) {
        alert(JSON.stringify(event.schedule));
        var schedule = event.schedule;
        //setShow(true);
 **HERE** 
      });`

**Comment by adhrinae** [comment]
https://nhn.github.io/tui.calendar/latest/Calendar#event-clickSchedule

There's an `event` property. so that you can access the native `MouseEvent`. Get the coordinates from that event.

**Comment by shakil-brl** [comment]
![image](https://user-images.githubusercontent.com/76032597/162175015-61bdd20f-4ab4-4ec1-9072-54b4ec590476.png)
**How can I customize this section with custom html elements** 
Thank you for your help

**Comment by adhrinae** [comment]
@shakil-brl 

There are only `'week.timegridSchedule.borderRadius'` and `'week.timegridSchedule.paddingLeft'` properties in theme options. you can modify them. and Try to override CSS of `tui-full-calendar-time-schedule` class and their children. you can find them with the browser devtools.
