### ISSUE TITLE
Alignment Issue

### ISSUE THREAD

**Issue by sjashwin** [nhn/toast-ui.react-calendar#74]
Version: 1.0.6

```js
<Calendar />
```

![Screenshot 2022-06-11 122818](https://user-images.githubusercontent.com/7351156/173202198-1330836c-3d7d-45dc-b713-c5d2ae87e72e.png)

This line
```html
<div class="tui-full-calendar-layout tui-view-1" style="background-color: white;"></div>
```
offsets the calendar by 800px by default

Fix
```js
<Calendar height="10px"/>
```

**Comment by adhrinae** [comment]
Yes, because it needs the `height` prop. and the default value is `800px`.

https://github.com/nhn/toast-ui.react-calendar/blob/master/src/index.js#L27-L30

You need to set the height of the container of the calendar in order to show it properly.
